ARG HAF_TAG=70974c14
ARG REGISTRY_IMAGE=registry.gitlab.syncad.com/hive/haf/

FROM ${REGISTRY_IMAGE}instance:${HAF_TAG} AS ai-instance

SHELL ["/bin/bash", "-c"]

USER root
WORKDIR /usr/local/src
COPY ./scripts/setup_ubuntu.sh /usr/local/src/scripts/

RUN bash -x ./scripts/setup_ubuntu.sh

USER haf_admin