rewrite ^/similarposts /rpc/get_similar_posts break;
# endpoint for get /similarposts

rewrite ^/$ / break;
# endpoint for openapi spec itself

rewrite ^/(.*)$ /rpc/$1 break;
# default endpoint for everything else
