rewrite ^/sync-settings /rpc/get_sync_settings break;
# endpoint for get /sync-settings

rewrite ^/embedding-updates /rpc/embedding_updates break;
# endpoint for get /embedding-updates

rewrite ^/thematiccontributors /rpc/find_thematic_contributors break;
# endpoint for get /thematiccontributors

rewrite ^/similarpostsbypost-one-shot /rpc/get_similar_posts_by_post_one_shot break;
# endpoint for get /similarpostsbypost-one-shot

rewrite ^/similarpostsbypost /rpc/get_similar_posts_by_post break;
# endpoint for get /similarpostsbypost

rewrite ^/similarposts-one-shot /rpc/get_similar_posts_one_shot break;
# endpoint for get /similarposts-one-shot

rewrite ^/similarposts /rpc/get_similar_posts break;
# endpoint for get /similarposts

rewrite ^/$ / break;
# endpoint for openapi spec itself

rewrite ^/(.*)$ /rpc/$1 break;
# default endpoint for everything else
