-- noqa: disable=CP03
SET ROLE hivesense_owner;

DO $BODY$
DECLARE 
  __schema_name VARCHAR;
  __vector_size INT := current_setting('PG_TEMP.VECTOR_SIZE', TRUE)::INT;
  __parallel_workers INT := current_setting('PG_TEMP.PARALLEL_WORKERS', TRUE)::INT;
  __store_halfvec_embeddings BOOLEAN := current_setting('PG_TEMP.STORE_HALFVEC_EMBEDDINGS', TRUE)::BOOLEAN;
  synchronization_stages hive.application_stages;
  __worker INT;
BEGIN
  SHOW SEARCH_PATH INTO __schema_name;

  ASSERT __parallel_workers IS NOT NULL, 'No parallel_workers';
  ASSERT __parallel_workers > 0, 'Parallel workers less than 0';

  synchronization_stages := ARRAY[( 'MASSIVE_PROCESSING', 11, 100000, '30 seconds' ), hive.live_stage()]::hive.application_stages;

  RAISE NOTICE 'HiveSense will be installed in schema % with context %', __schema_name, __schema_name;

  CREATE TABLE IF NOT EXISTS hivesense_app_status
  (
    id SERIAL PRIMARY KEY,
    continue_processing BOOLEAN NOT NULL,
    parallel_workers INT,
    llm TEXT,
    ollama TEXT,
    start_block INT,
    embedding_batch_size INT, -- send this many texts to ollama in a single API call, it will generate this many embedding vectors and sent them back
    tokenizer_model TEXT, -- model used for counting tokens, must be compatible with `llm`'s tokenizer
    tokens_per_chunk INT, -- for chunking posts, number of tokens per chunk (should not `llm`'s the model's max tokens)
    overlap_amount REAL, -- for chunking posts, try to include this amount of overlap with the prevoius chunk to add context (0.15 = 15%)
    use_halfvec_index BOOLEAN NOT NULL DEFAULT false, -- if true, index using 16-bit floats, slight loss of accuracy
    store_halfvec_embeddings BOOLEAN NOT NULL DEFAULT false, -- if true, store embeddings as halfvec
    document_prefix     TEXT    NOT NULL DEFAULT 'passage: ', -- prefix used when generating embeddings from posts
    query_prefix        TEXT    NOT NULL DEFAULT 'query: ', -- prefix used when generating embeddings from query strings
    embedding_dimensionality INT NOT NULL DEFAULT 768, -- size of embedding vectors generated by `llm`
    min_token_threshold INT NOT NULL DEFAULT 75, -- don't generate embeddings for posts shorter than this number of tokens
    min_token_search_threshold INT NOT NULL DEFAULT 0, -- ignore posts < this size when *searching* (0 = disabled)
    max_embeddings_per_post INT, -- max number of chunks per post, NULL for unlimited
    advisory_lock_namespace_begin INT, -- start of advisory lock namespace, if running multiple instances, use different values (separated by, say, 10 or so)
    max_visible_sync_seq INT NOT NULL DEFAULT 0, -- highest sync sequence number to publish, anything higher may have gaps that will be filled later
    syncing_embeddings BOOLEAN, -- true if we're syncing emeddings, false if computing locally
    sync_uuid uuid -- uuid tracking what server we're syncing embeddings from (or whether we're generating them ourselves)
  );

  IF NOT hive.app_context_exists(__schema_name) THEN
    PERFORM hive.app_create_context(_name => __schema_name,
                                    _schema => __schema_name,
                                    _is_forking => False,
                                    _stages => synchronization_stages);
  END IF;

  CREATE TABLE IF NOT EXISTS version(
    schema_hash TEXT,
    runtime_hash TEXT
  );

  -- Monotonic sequence that orders every logical operation
  CREATE SEQUENCE IF NOT EXISTS hivesense_app.sync_seq;

  -- This table will hold, for every post_id that we generate embeddings for,
  -- the total number of tokens in that post.  We insert one row per post_id.
  CREATE TABLE IF NOT EXISTS hivesense_app.post_data
  (
      post_id            INT PRIMARY KEY REFERENCES hivemind_app.hive_posts(id),
      number_of_tokens   INT NOT NULL,
      last_vectors_block INT NOT NULL DEFAULT -1
  );

  -- extend to public, to find vector from pgvector
  EXECUTE format( 'SET SEARCH_PATH TO %s, public', __schema_name );
  IF __store_halfvec_embeddings THEN
    EXECUTE format($$
      CREATE TABLE IF NOT EXISTS posts_vectors
      (
          post_id      INT NOT NULL REFERENCES hivesense_app.post_data(post_id),
          chunk_number INT NOT NULL,
          embedding    public.halfvec(%s) NOT NULL,
          sync_seq     INT NOT NULL,          -- drawn from hivesense_app.sync_seq
          PRIMARY KEY (post_id, chunk_number)
      );
    $$, __vector_size);
  ELSE
    EXECUTE format($$
      CREATE TABLE IF NOT EXISTS posts_vectors
      (
          post_id      INT NOT NULL REFERENCES hivesense_app.post_data(post_id),
          chunk_number INT NOT NULL,
          embedding    vector(%s) NOT NULL,
          sync_seq     INT NOT NULL,          -- drawn from hivesense_app.sync_seq
          PRIMARY KEY (post_id, chunk_number)
      );
    $$, __vector_size);
  END IF;
  -- Helpful index for “give me everything > after_seq”
  CREATE INDEX IF NOT EXISTS posts_vectors_sync_seq_post_id_idx ON hivesense_app.posts_vectors(sync_seq, post_id);

  -- the current version of sqlfluff doesn't understand 'GRANT MAINTAIN'
  EXECUTE format( 'GRANT MAINTAIN ON ALL TABLES IN SCHEMA %s TO hived_group' , __schema_name );
  EXECUTE format( 'GRANT ALL ON SCHEMA %s TO hived_group' , __schema_name );

  END
$BODY$;

INSERT INTO hivesense_app_status
(
  id,
  continue_processing,
  parallel_workers,
  llm,
  ollama,
  start_block,
  embedding_batch_size,
  tokenizer_model,
  tokens_per_chunk,
  overlap_amount,
  use_halfvec_index,
  store_halfvec_embeddings,
  document_prefix,
  query_prefix,
  embedding_dimensionality,
  min_token_threshold,
  min_token_search_threshold,
  max_embeddings_per_post,
  advisory_lock_namespace_begin,
  max_visible_sync_seq,
  syncing_embeddings,
  sync_uuid
)
VALUES
(
    1,
    TRUE,
    current_setting('PG_TEMP.PARALLEL_WORKERS', TRUE)::INT,
    current_setting('PG_TEMP.LLM', TRUE)::TEXT,
    current_setting('PG_TEMP.OLLAMA_HOST', TRUE)::TEXT,
    current_setting('PG_TEMP.START_BLOCK', TRUE)::INT,
    current_setting('PG_TEMP.EMBEDDING_BATCH_SIZE', TRUE)::INT,
    current_setting('PG_TEMP.TOKENIZER_MODEL', TRUE)::TEXT,
    current_setting('PG_TEMP.TOKENS_PER_CHUNK', TRUE)::INT,
    current_setting('PG_TEMP.OVERLAP_AMOUNT', TRUE)::REAL,
    current_setting('PG_TEMP.USE_HALFVEC_INDEX', TRUE)::BOOLEAN,
    current_setting('PG_TEMP.STORE_HALFVEC_EMBEDDINGS', TRUE)::BOOLEAN,
    current_setting('PG_TEMP.DOCUMENT_PREFIX', TRUE)::TEXT,
    current_setting('PG_TEMP.QUERY_PREFIX', TRUE)::TEXT,
    current_setting('PG_TEMP.VECTOR_SIZE', TRUE)::INT,
    current_setting('PG_TEMP.MIN_TOKEN_THRESHOLD', TRUE)::INT,
    current_setting('PG_TEMP.MIN_TOKEN_SEARCH_THRESHOLD', TRUE)::INT,
    NULLIF(current_setting('PG_TEMP.MAX_EMBEDINGS_PER_POST', TRUE)::INT, 0),
    10000, -- advisory_lock_namespace_begin
    0,     -- max_visible_sync_seq
    NULL,  -- syncing_embeddings
    NULL   -- sync_uuid
)
ON CONFLICT (id)
DO UPDATE SET
ollama = excluded.ollama,
embedding_batch_size = excluded.embedding_batch_size;
-- only ollama host and batch size can be overridden by subsequent install
-- changing llm model or number of host requires resync

CREATE SEQUENCE IF NOT EXISTS hivesense_app.batch_seq START 1;

CREATE TABLE IF NOT EXISTS hivesense_app.block_tasks (
  task_id     SERIAL PRIMARY KEY,
  batch_id    BIGINT   NOT NULL,
  shard       INT,          -- worker number (1…N), NULL if unclaimed
  first_block INT      NOT NULL,
  last_block  INT      NOT NULL,
  post_ids    INT[]    NOT NULL DEFAULT '{}',
  status      TEXT     NOT NULL DEFAULT 'pending',   -- pending | running | done
  claimed_at  TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS block_tasks_pending_idx ON hivesense_app.block_tasks (status, shard);

-- Table that records logical deletions
CREATE TABLE IF NOT EXISTS hivesense_app.deleted_embeddings (
    post_id  INT     NOT NULL REFERENCES hivesense_app.post_data (post_id),
    sync_seq INT     NOT NULL UNIQUE,
    PRIMARY KEY (post_id, sync_seq)
);

CREATE INDEX IF NOT EXISTS deleted_embeddings_sync_seq_post_id_idx ON hivesense_app.deleted_embeddings(sync_seq, post_id);

RESET ROLE;
