-- noqa: disable=CP03
SET ROLE hivesense_owner;

DO $BODY$
DECLARE 
  __schema_name VARCHAR;
  __vector_size INT := current_setting('PG_TEMP.VECTOR_SIZE', TRUE)::INT;
  __parallel_workers INT := current_setting('PG_TEMP.PARALLEL_WORKERS', TRUE)::INT;
  synchronization_stages hive.application_stages;
  __worker INT;
BEGIN
  SHOW SEARCH_PATH INTO __schema_name;

  ASSERT __parallel_workers IS NOT NULL, 'No parallel_workers';
  ASSERT __parallel_workers > 0, 'Parallel workers less than 0';

  synchronization_stages := ARRAY[( 'MASSIVE_PROCESSING', 11, 10000, '30 seconds' ), hive.live_stage()]::hive.application_stages;

  RAISE NOTICE 'HiveSense will be installed in schema % with context %', __schema_name, __schema_name;

  FOR __worker IN 1..__parallel_workers LOOP
          IF hive.app_context_exists(__schema_name || __worker) THEN
              RAISE NOTICE 'Context % already exists, it means all tables are already created and data installing is skipped', __schema_name || __worker;
              CONTINUE;
          END IF;

          PERFORM hive.app_create_context(
                  _name => __schema_name || __worker ,
                  _schema => __schema_name || __worker,
                  _is_forking => False,
                  _stages => synchronization_stages
             );
  END LOOP;

CREATE TABLE IF NOT EXISTS hivesense_app_status
(
  id SERIAL PRIMARY KEY,
  continue_processing BOOLEAN NOT NULL,
  parallel_workers INT,
  llm TEXT,
  ollama TEXT,
  start_block INT,
  embedding_batch_size INT, -- send this many texts to ollama in a single API call, it will generate this many embedding vectors and sent them back
  tokenizer_model TEXT, -- model used for counting tokens, must be compatible with `llm`'s tokenizer
  tokens_per_chunk INT, -- for chunking posts, number of tokens per chunk (should not `llm`'s the model's max tokens)
  overlap_amount REAL, -- for chunking posts, try to include this amount of overlap with the prevoius chunk to add context (0.15 = 15%)
  sentence_language_model TEXT, -- model for detecting sentence boundaries
  use_halfvec_index BOOLEAN NOT NULL DEFAULT false, -- if true, index using 16-bit floats, slight loss of accuracy
  document_prefix     TEXT    NOT NULL DEFAULT 'passage: ', -- prefix used when generating embeddings from posts
  query_prefix        TEXT    NOT NULL DEFAULT 'query: ', -- prefix used when generating embeddings from query strings
  embedding_dimensionality INT NOT NULL DEFAULT 768, -- size of embedding vectors generated by `llm`
  min_token_threshold INT NOT NULL DEFAULT 75, -- don't generate embeddings for posts shorter than this number of tokens
  max_embeddings_per_post INT -- max number of chunks per post, NULL for unlimited
);

CREATE TABLE IF NOT EXISTS version(
  schema_hash TEXT,
  runtime_hash TEXT
);

-- extend to public, to find vector from pgvector
EXECUTE format( 'SET SEARCH_PATH TO %s, public', __schema_name );

EXECUTE format($$
            CREATE TABLE IF NOT EXISTS posts_vectors
            (
                post_id INT NOT NULL,
                embedding vector( %s ) NOT NULL
            );
            $$, __vector_size
);

-- the current version of sqlfluff doesn't understand 'GRANT MAINTAIN'
EXECUTE format( 'GRANT MAINTAIN ON ALL TABLES IN SCHEMA %s TO hived_group' , __schema_name );
EXECUTE format( 'GRANT ALL ON SCHEMA %s TO hived_group' , __schema_name );

  END
$BODY$;

INSERT INTO hivesense_app_status
(
  id,
  continue_processing,
  parallel_workers,
  llm,
  ollama,
  start_block,
  embedding_batch_size,
  tokenizer_model,
  tokens_per_chunk,
  overlap_amount,
  sentence_language_model,
  use_halfvec_index,
  document_prefix,
  query_prefix,
  embedding_dimensionality,
  min_token_threshold,
  max_embeddings_per_post
)
VALUES
(
    1,
    TRUE,
    current_setting('PG_TEMP.PARALLEL_WORKERS', TRUE)::INT,
    current_setting('PG_TEMP.LLM', TRUE)::TEXT,
    current_setting('PG_TEMP.OLLAMA_HOST', TRUE)::TEXT,
    current_setting('PG_TEMP.START_BLOCK', TRUE)::INT,
    current_setting('PG_TEMP.EMBEDDING_BATCH_SIZE', TRUE)::INT,
    current_setting('PG_TEMP.TOKENIZER_MODEL', TRUE)::TEXT,
    current_setting('PG_TEMP.TOKENS_PER_CHUNK', TRUE)::INT,
    current_setting('PG_TEMP.OVERLAP_AMOUNT', TRUE)::REAL,
    current_setting('PG_TEMP.SENTENCE_LANGUAGE_MODEL', TRUE)::TEXT,
    current_setting('PG_TEMP.USE_HALFVEC_INDEX', TRUE)::BOOLEAN,
    current_setting('PG_TEMP.DOCUMENT_PREFIX', TRUE)::TEXT,
    current_setting('PG_TEMP.QUERY_PREFIX', TRUE)::TEXT,
    current_setting('PG_TEMP.VECTOR_SIZE', TRUE)::INT,
    current_setting('PG_TEMP.MIN_TOKEN_THRESHOLD', TRUE)::INT,
    NULLIF(current_setting('PG_TEMP.MAX_EMBEDINGS_PER_POST', TRUE)::INT, 0)
)
ON CONFLICT (id)
DO UPDATE SET
ollama = excluded.ollama,
embedding_batch_size = excluded.embedding_batch_size;
-- only ollama host and batch size can be overridden by subsequent install
-- changing llm model or number of host requires resync

RESET ROLE;
